In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report,confusion_matrix

In [3]:
df = pd.read_csv("yeni_egitim_verisi.csv")
df.head()

,subject,clean_body,sender_domain,send_hour,label
0,"""ÖDÜLLÜ ""OSTİM Teknik Üniversitesi - Yükseköğr...","Sevgili Öğrencilerimiz, YÖK'ün üniversitemizi ...",ostimteknik.edu.tr,12,ham
1,"""ÖDÜLLÜ ""OSTİM Teknik Üniversitesi - Yükseköğr...","Sevgili Öğrencilerimiz, YÖK'ün üniversitemizi ...",ostimteknik.edu.tr,12,ham
2,save on united now and get 30 % off a future f...,dear expedia . com traveler now you can save t...,NaN,12,ham
3,NaN,[ILUG] Hayes Accura ISDN PCIDoes anyone know i...,NaN,12,ham
4,NaN,Dawn raids stoke fires of resentmentURL: http:...,NaN,12,ham

In [4]:
df.isnull().sum()

subject           82
clean_body        43
sender_domain    285
send_hour          0
label              0
dtype: int64

In [5]:
df = df.dropna() #null degerleri dropla

In [6]:
df.isnull().sum()

subject          0
clean_body       0
sender_domain    0
send_hour        0
label            0
dtype: int64

In [7]:
df.loc[df['label'] == 'phishing','label'] = 2
df.loc[df['label'] == 'spam','label'] = 1
df.loc[df['label'] == 'ham','label'] = 0

In [8]:
df['text'] = df['subject'] + df['clean_body']

In [9]:
df

,subject,clean_body,sender_domain,send_hour,label,text
0,"""ÖDÜLLÜ ""OSTİM Teknik Üniversitesi - Yükseköğr...","Sevgili Öğrencilerimiz, YÖK'ün üniversitemizi ...",ostimteknik.edu.tr,12,0,"""ÖDÜLLÜ ""OSTİM Teknik Üniversitesi - Yükseköğr..."
1,"""ÖDÜLLÜ ""OSTİM Teknik Üniversitesi - Yükseköğr...","Sevgili Öğrencilerimiz, YÖK'ün üniversitemizi ...",ostimteknik.edu.tr,12,0,"""ÖDÜLLÜ ""OSTİM Teknik Üniversitesi - Yükseköğr..."
152,Re: Zoot apt/openssh & new DVD playing doc,"On Tue, 2002-10-08 at 10:36, Matthias Saou wro...",ckloiber.com,12,0,Re: Zoot apt/openssh & new DVD playing docOn T...
153,Re: Optical analog computing?,"--- begin forwarded text Date: Thu, 03 Oct 200...",shipwright.com,12,0,Re: Optical analog computing?--- begin forward...
154,xine src packge still gives errors,Hi I try to rebuild xine from src package and ...,punkass.com,12,0,xine src packge still gives errorsHi I try to ...
...,...,...,...,...,...,...
6280,Microsoft account unusual signin activity,Microsoft account Unusual sign.in activity We ...,access-accsecurity.com,12,2,Microsoft account unusual signin activityMicro...
6281,Microsoft account unusual signin activity,Microsoft account Unusual sign.in activity We ...,access-accsecurity.com,12,2,Microsoft account unusual signin activityMicro...
6282,Microsoft account unusual signin activity,Microsoft account Unusual sign.in activity We ...,access-accsecurity.com,12,2,Microsoft account unusual signin activityMicro...
6283,"Rodrigo-f-p, Urgent: Account Verification Requ...",----------------------------------------------...,mjnpanbt.zendesk.com,12,2,"Rodrigo-f-p, Urgent: Account Verification Requ..."
6284,"Rodrigo-f-p, your wallet is still pending veri...",----------------------------------------------...,qsrrnhrb.zendesk.com,12,2,"Rodrigo-f-p, your wallet is still pending veri..."

In [10]:
X = df['text']
y = df['label']

In [11]:
X_train, X_test,y_train, y_test = train_test_split(X,y, test_size= 0.3, random_state= 42)

In [12]:
X_train = X_train.fillna('')
X_test = X_test.fillna('')
y_train = y_train.fillna('')
y_test = y_test.fillna('')

C:\Users\fatih\AppData\Local\Temp\ipykernel_34180\1185381603.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y_train = y_train.fillna('')
C:\Users\fatih\AppData\Local\Temp\ipykernel_34180\1185381603.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y_test = y_test.fillna('')

In [13]:
X # controlleri saglayalim

0       "ÖDÜLLÜ "OSTİM Teknik Üniversitesi - Yükseköğr...
1       "ÖDÜLLÜ "OSTİM Teknik Üniversitesi - Yükseköğr...
152     Re: Zoot apt/openssh & new DVD playing docOn T...
153     Re: Optical analog computing?--- begin forward...
154     xine src packge still gives errorsHi I try to ...
                              ...
6280    Microsoft account unusual signin activityMicro...
6281    Microsoft account unusual signin activityMicro...
6282    Microsoft account unusual signin activityMicro...
6283    Rodrigo-f-p, Urgent: Account Verification Requ...
6284    Rodrigo-f-p, your wallet is still pending veri...
Name: text, Length: 5945, dtype: object

In [14]:
y

0       0
1       0
152     0
153     0
154     0
       ..
6280    2
6281    2
6282    2
6283    2
6284    2
Name: label, Length: 5945, dtype: object

In [15]:
feature_extraction = TfidfVectorizer(lowercase= True, ngram_range=(1,2))

In [16]:
X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)

In [17]:
svm = SVC()
svm.fit(X_train_features, y_train)

svm_train = svm.predict(X_train_features)
svm_test = svm.predict(X_test_features)


svm_train_acc = accuracy_score(y_train,svm_train)
svm_test_acc = accuracy_score(y_test, svm_test)

svmpre = precision_score(y_test,svm_test, average='weighted')
svmrec = recall_score(y_test,svm_test,average='weighted')
svmf1 = f1_score(y_test,svm_test,average='weighted')

In [18]:
print("SVM metrikleri")
print("\nTrain Accuracy score:" ,svm_train_acc)
print("\nTest Accuracy score:", svm_test_acc)
print("\nPrecision Score:", svmpre)
print("\nRecall Score:", svmrec)
print("\nF1 Score:", svmf1)
print("\n Classification Report :", classification_report(y_test,svm_test)) 
print("\n Confusion matrix :",confusion_matrix(y_test,svm_test))

SVM metrikleri

Train Accuracy score: 0.9935111751982696

Test Accuracy score: 0.9702914798206278

Precision Score: 0.9702111896652905

Recall Score: 0.9702914798206278

F1 Score: 0.9702004801270595

 Classification Report :               precision    recall  f1-score   support

           0       0.98      0.99      0.99       715
           1       0.96      0.94      0.95       434
           2       0.96      0.97      0.96       635

    accuracy                           0.97      1784
   macro avg       0.97      0.97      0.97      1784
weighted avg       0.97      0.97      0.97      1784


 Confusion matrix : [[710   2   3]
 [  5 407  22]
 [  7  14 614]]

***Overfitting yok ve basari oranlari yuksek***

In [19]:
df2 = pd.read_csv('xgboost_data_v2.csv')